export const Images = {
  eyeShow: require('./pngs/eyeShow.png'),
  eyeHide: require('./pngs/eyeHide.png'),
  close: require('./pngs/close.png'),
  home: require('./pngs/home.png'),
  logout: require('./pngs/logout.png'),
  downArrow: require('./pngs/downArrow.png'),
  logo: require('./pngs/logo.png'),
  camera: require('./pngs/camera.png'),
  gallery: require('./pngs/gallery.png'),
  add:require('./pngs/add.png'),
  minus:require('./pngs/minus.png'),
  helmet:require('./pngs/helmet.png'),
  check:require('./pngs/check.png'),
  bottom_curve:require('./pngs/bottom_curve.png'),
  checked:require('./pngs/checked.png'),
  profile: require('./pngs/profile.png'),
  camera_lien:require('./pngs/camera_lien.png'),
  photo:require('./pngs/photo.png'),
};
