export const Images = {
  eyeShow: require('./pngs/eyeShow.png'),
  eyeHide: require('./pngs/eyeHide.png'),
  leftArrow: require('./pngs/leftArrow.png'),
  rightArrow: require('./pngs/rightArrow.png'),
  messageIcon: require('./pngs/message.png'),
  dotArrowIcon: require('./pngs/dotArrow.png'),
  editIcon: require('./pngs/edit.png'),
  calendarIcon: require('./pngs/calendar.png'),
  messages: require('./pngs/messages.png'),
  search: require('./pngs/search.png'),
  close: require('./pngs/close.png'),
  checkUser: require('./pngs/checkUser.png'),
  home: require('./pngs/home.png'),
  logout: require('./pngs/logout.png'),
  right: require('./pngs/right.png'),
  lead: require('./pngs/lead.png'),
  visit: require('./pngs/visit.png'),
  service: require('./pngs/service.png'),
  phone: require('./pngs/phone.png'),
  user: require('./pngs/user.png'),
  support: require('./pngs/support.png'),
  file: require('./pngs/file.png'),
  checkout: require('./pngs/checkout.png'),
  location_mark: require('./pngs/location_mark.png'),
  notification: require('./pngs/notification.png'),
  more: require('./pngs/more.png'),
  downArrow: require('./pngs/downArrow.png'),
  person: require('./pngs/person.png'),
  clock: require('./pngs/clock.png'),
  plus: require('./pngs/plus.png'),
  edit: require('./pngs/edit.png'),
  info: require('./pngs/info.png'),
  delete: require('./pngs/bin.png'),
  elevator: require('./pngs/elevator.png'),
  repair: require('./pngs/repair.png'),
  enquiry: require('./pngs/enquiry.png'),
  logo: require('./pngs/logo.png'),
  expense: require('./pngs/expense.png'),
  profile: require('./pngs/profile.png'),
  userFill:require('./pngs/userFill.png'),
  arroba:require('./pngs/arroba.png'),
  phoneCall:require('./pngs/phoneCall.png'),
  group:require('./pngs/group.png'),
  camera: require('./pngs/camera.png'),
  gallery: require('./pngs/gallery.png'),
  materials: require('./pngs/materials.png'),
  update: require('./pngs/update.png'),
  filter:require('./pngs/filter.png'),
  add:require('./pngs/add.png'),
  minus:require('./pngs/minus.png'),
  helmet:require('./pngs/helmet.png'),
  male:require('./pngs/male.png'),
  female:require('./pngs/female.png'),
  maleFemale:require('./pngs/maleFemale.png'),
  derrick:require('./pngs/derrick.png'),
  check:require('./pngs/check.png'),
  sun:require('./pngs/sun.png'),
  moon:require('./pngs/moon.png'),
  dpr:require('./pngs/dpr.png'),
  userModel:require('./pngs/userModel.png'),
  extracurricular:require('./pngs/extracurricular.png'),
  complaint:require('./pngs/complaint.png'),
  checkList:require('./pngs/checklist.png'),
  login_bg:require('./pngs/login_bg.png'),
  bottom_curve:require('./pngs/bottom_curve.png'),
  breakTime:require('./pngs/breakTime.png'),
  refresh:require('./pngs/refresh.png'),
  circleClose:require('./pngs/circleClose.png'),
  camera_lien:require('./pngs/camera_lien.png'),
  photo:require('./pngs/photo.png'),
  pdf:require('./pngs/pdf.png'),
  deliveryTruck:require('./pngs/deliveryTruck.png'),
  r_pm:require('./pngs/r_pm.png'),
  r_m:require('./pngs/r_m.png'),
  r_p:require('./pngs/r_p.png'),
  like:require('./pngs/like.png'),
  order_done:require('./pngs/order_done.png'),
  chat_background:require('./pngs/chat_background.png'),
  send:require('./pngs/send.png'),
  clip:require('./pngs/clip.png'),
  leave:require('./pngs/leave.png'),
};
